---
name: plc
description: A new Flutter project.
publish_to: none
version: 1.1.5+8
environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: 3.35.5
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: "^9.1.1"
  dio: "^5.5.0+1"
  get_it: "^8.2.0"
  google_fonts: "^6.3.2"
  mockito: "^5.5.0"
  gsheets: "^0.5.0"
  envied: "^1.3.1"
  url_launcher: "^6.3.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"
  bloc_test: "^10.0.0"
  envied_generator: "^1.3.1"
  build_runner: "^2.7.1"
flutter:
  uses-material-design: true
  assets:
  - images/plc.jpg
